# Generated by Django 4.2.6 on 2023-12-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campi',
            fields=[
                ('id_campi', models.AutoField(primary_key=True, serialize=False)),
                ('cod_campi', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_campi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('cod_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('turma_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('turno_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('periodo_curso', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id_discente', models.AutoField(primary_key=True, serialize=False)),
                ('mat_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('ingresso_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('curso_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('nascimento_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_curso_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('email_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('fomr_ing_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('mun_res_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('naturalidade_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('resp_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('status_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('tel_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('origem_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('turma_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('zona_discente', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disc', models.AutoField(primary_key=True, serialize=False)),
                ('sigla_disc', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_disc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('cod_docente', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_docente', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nome_nivel', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('ano_periodo', models.CharField(blank=True, max_length=200, null=True)),
                ('semestre_periodo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id_diario', models.AutoField(primary_key=True, serialize=False)),
                ('cod_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_diario_componente', models.CharField(blank=True, max_length=200, null=True)),
                ('siape_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('docente_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('ch_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('ch_aula_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_curso_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('turma_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_curso_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('turno_curso_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('periodo_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('campus_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('qtd_aluno_diario', models.CharField(blank=True, max_length=200, null=True)),
                ('turma_discente', models.ForeignKey(blank=True, db_column='turma_discente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.discente')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('id_campi', models.ForeignKey(blank=True, db_column='id_campi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.campi')),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.curso')),
                ('id_disc', models.ForeignKey(blank=True, db_column='id_disc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.disciplina')),
                ('id_discente', models.ForeignKey(blank=True, db_column='id_discente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.discente')),
                ('id_docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.docente')),
                ('id_nivel', models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.nivel')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Avadoc',
            fields=[
                ('id_avadoc', models.AutoField(primary_key=True, serialize=False)),
                ('assid_avadoc', models.CharField(blank=True, max_length=200)),
                ('pont_avadoc', models.CharField(blank=True, max_length=200)),
                ('plan_avadoc', models.CharField(blank=True, max_length=200)),
                ('realiza_avadoc', models.CharField(blank=True, max_length=200)),
                ('avaliacao_avadoc', models.CharField(blank=True, max_length=200)),
                ('postura_avadoc', models.CharField(blank=True, max_length=200)),
                ('id_doc', models.CharField(blank=True, max_length=200, null=True)),
                ('user_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('id_docente', models.ForeignKey(blank=True, db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.docente')),
            ],
        ),
    ]
